// Generátor vtipných anonymních jmen ve stylu Google Docs (např. Anonymní Pelikán)
export const GOOGLE_STYLE_ANIMALS = [
  "Pelikán",
  "Kapybara",
  "Lenochod",
  "Lemur",
  "Vydra",
  "Panda",
  "Medojed",
  "Koala",
  "Jezevec",
  "Chobotnice",
  "Chameleon",
  "Veverka",
  "Alpaka",
  "Surikata",
  "Narval",
  "Ptakopysk",
  "Bobr",
  "Dikobraz",
  "Kivi",
  "Šimpanz",
  "Křeček",
  "Wombat",
  "Ježek",
  "Axolotl",
  "Tučňák",
  "Klokan",
  "Gepard",
  "Plameňák",
  "Rypoš",
  "Mýval",
  "Lasička",
  "Papuchalk",
  "Tukan",
  "Tapír",
  "Pásovec",
  "Dingo",
  "Rosomák",
  "Kočkodan",
  "Delfín",
  "Sysel",
  "Kormorán",
  "Ledňáček",
  "Mravenečník",
  "Lenochoďák",
];

export function getRandomAnonymousName(): string {
  const animal = GOOGLE_STYLE_ANIMALS[Math.floor(Math.random() * GOOGLE_STYLE_ANIMALS.length)];
  return `Anonymní ${animal}`;
}
